terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

############################
# S3 BUCKETS
############################
resource "aws_s3_bucket" "raw" {
  bucket = "s3-layer-raw"
}

resource "aws_s3_bucket" "refined" {
  bucket = "s3-layer-refined"
}

resource "aws_s3_bucket" "spec" {
  bucket = "s3-layer-spec"
}

resource "aws_s3_bucket" "ml" {
  bucket = "s3-layer-machine-learning-v2"
}

resource "aws_s3_bucket" "captura" {
  bucket = "s3-layer-captura"
}

############################
# KINESIS
############################
resource "aws_kinesis_stream" "data_stream" {
  name             = "Kinesis-layer-refined"
  shard_count      = 1
  retention_period = 24
}

############################
# SNS
############################
resource "aws_sns_topic" "raw_topic" {
  name = "sqs-layer-raw"
}

############################
# IAM ROLE LAMBDA (EXISTENTE)
############################
resource "aws_iam_role" "lambda_role" {
  name = "lambda_pipeline_role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Principal = {
        Service = "lambda.amazonaws.com"
      }
      Effect = "Allow"
    }]
  })
}

############################
# LAMBDA (EXISTENTE)
############################
resource "aws_lambda_function" "trigger_kinesis" {
  function_name    = "lambda-send-kinesis"
  role             = aws_iam_role.lambda_role.arn
  runtime          = "python3.9"
  handler          = "index.handler"
  filename         = "lambda.zip"
  source_code_hash = filebase64sha256("lambda.zip")

  environment {
    variables = {
      STREAM_NAME = aws_kinesis_stream.data_stream.name
    }
  }
}

############################
# NOVA LAMBDA - CAMADA RAW
############################
resource "aws_iam_role" "lambda_raw_role" {
  name = "lambda-raw-layer-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Principal = {
        Service = "lambda.amazonaws.com"
      }
      Effect = "Allow"
    }]
  })
}

resource "aws_lambda_function" "raw_event_lambda" {
  function_name    = "lambda-raw-layer-processor"
  role             = aws_iam_role.lambda_raw_role.arn
  runtime          = "python3.9"
  handler          = "index.handler"
  filename         = "lambda_raw.zip"
  source_code_hash = filebase64sha256("lambda_raw.zip")

  environment {
    variables = {
      RAW_BUCKET = aws_s3_bucket.raw.bucket
    }
  }
}

############################
# EVENTBRIDGE - RAW LAYER
############################
resource "aws_cloudwatch_event_rule" "raw_event_rule" {
  name        = "eventbridge-raw-layer-trigger"
  description = "Dispara a Lambda da camada RAW"

  schedule_expression = "rate(5 minutes)"
}

resource "aws_cloudwatch_event_target" "raw_lambda_target" {
  rule      = aws_cloudwatch_event_rule.raw_event_rule.name
  target_id = "lambdaRawTarget"
  arn       = aws_lambda_function.raw_event_lambda.arn
}

resource "aws_lambda_permission" "allow_eventbridge_raw" {
  statement_id  = "AllowExecutionFromEventBridgeRaw"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.raw_event_lambda.function_name
  principal     = "events.amazonaws.com"
  source_arn    = aws_cloudwatch_event_rule.raw_event_rule.arn
}

############################
# SNS -> LAMBDA
############################
resource "aws_sns_topic_subscription" "lambda_sub" {
  topic_arn = aws_sns_topic.raw_topic.arn
  protocol  = "lambda"
  endpoint  = aws_lambda_function.trigger_kinesis.arn
}

############################
# IAM ROLE GLUE
############################
resource "aws_iam_role" "glue_role" {
  name = "glue-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = {
        Service = "glue.amazonaws.com"
      }
      Action = "sts:AssumeRole"
    }]
  })
}

############################
# GLUE JOBS
############################
resource "aws_glue_job" "capture_raw" {
  name     = "gluejob-capture-raw"
  role_arn = aws_iam_role.glue_role.arn

  command {
    script_location = "s3://aws-glue-assets-271547278649-us-east-1/scripts/gluejob-capture-raw.py"
    python_version  = "3"
  }

  glue_version = "5.0"
}

resource "aws_glue_job" "raw_refined" {
  name     = "gluejob-raw-refined"
  role_arn = aws_iam_role.glue_role.arn

  command {
    script_location = "s3://aws-glue-assets-271547278649-us-east-1/scripts/gluejob-raw-refined.py"
    python_version  = "3"
  }

  glue_version = "5.0"
}

resource "aws_glue_job" "refined_spec" {
  name     = "gluejob-refined-spec"
  role_arn = aws_iam_role.glue_role.arn

  command {
    script_location = "s3://aws-glue-assets-271547278649-us-east-1/scripts/gluejob-refined-spec.py"
    python_version  = "3"
  }

  glue_version = "5.0"
}

############################
# ATHENA
############################
resource "aws_athena_workgroup" "athena_spec" {
  name = "spec-workgroup"

  configuration {
    result_configuration {
      output_location = "s3://${aws_s3_bucket.spec.bucket}/athena-results/"
    }
  }
}
